-- Enable extension for UUID if needed, though we use bigints for general IDs
create extension if not exists "uuid-ossp";

-- Create function to update update_at timestamp automatically
create or replace function update_modified_column()
returns trigger as $$
begin
    new.update_at = now();
    return new;
end;
$$ language plpgsql;

-- 1. Users Table
create table if not exists users (
    id bigint generated by default as identity primary key,
    full_name varchar(255) not null,
    email varchar(255) unique not null,
    password varchar(255) not null,
    create_at timestamp with time zone default timezone('utc'::text, now()) not null,
    update_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_users_modtime
    before update on users
    for each row
    execute function update_modified_column();

-- 2. Provider Drama Table
create table if not exists provider_drama (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    slug varchar(255) unique not null,
    create_at timestamp with time zone default timezone('utc'::text, now()) not null,
    update_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_provider_drama_modtime
    before update on provider_drama
    for each row
    execute function update_modified_column();

-- 3. Drama Table
create table if not exists drama (
    id bigint generated by default as identity primary key,
    id_provider_drama bigint references provider_drama(id) on delete cascade not null,
    title varchar(255) not null,
    slug varchar(255) unique not null,
    deskripsi text,
    total_episode integer default 0 not null,
    cover_imagekit_url text,
    create_at timestamp with time zone default timezone('utc'::text, now()) not null,
    update_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_drama_modtime
    before update on drama
    for each row
    execute function update_modified_column();
    

-- 4. Episode Table
create table if not exists episode (
    id bigint generated by default as identity primary key,
    id_drama bigint references drama(id) on delete cascade not null,
    episode integer not null,
    url text not null,
    create_at timestamp with time zone default timezone('utc'::text, now()) not null,
    update_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_episode_modtime
    before update on episode
    for each row
    execute function update_modified_column();

-- 5. Imagekit API Table
create table if not exists imagekit_api (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    public_key text not null,
    private_key text not null,
    endpoint_url text not null,
    create_at timestamp with time zone default timezone('utc'::text, now()) not null,
    update_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create trigger update_imagekit_api_modtime
    before update on imagekit_api
    for each row
    execute function update_modified_column();
